"""
Report generation endpoints.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from sqlalchemy.orm import Session

from backend import models
from backend.auth import get_current_user
from backend.database import get_db
from backend.routers.assessments import _assessment_summary, _control_dict

router = APIRouter(prefix="/api/reports", tags=["reports"])

ML_COLORS = {0: "#dc2626", 1: "#f97316", 2: "#eab308", 3: "#16a34a"}


@router.get("/{assessment_id}/json")
def report_json(
    assessment_id: int,
    db: Session = Depends(get_db),
    _: models.User = Depends(get_current_user),
):
    a = db.query(models.Assessment).filter_by(id=assessment_id).first()
    if not a:
        raise HTTPException(status_code=404, detail="Assessment not found")
    return JSONResponse(content={
        **_assessment_summary(a),
        "controls": [_control_dict(cr) for cr in a.control_results],
    })


@router.get("/{assessment_id}/html", response_class=HTMLResponse)
def report_html(
    assessment_id: int,
    db: Session = Depends(get_db),
    _: models.User = Depends(get_current_user),
):
    a = db.query(models.Assessment).filter_by(id=assessment_id).first()
    if not a:
        raise HTTPException(status_code=404, detail="Assessment not found")

    machine = a.machine
    overall_color = ML_COLORS.get(a.overall_maturity, "#6b7280")

    rows = ""
    for cr in sorted(a.control_results, key=lambda x: x.control_id):
        c = ML_COLORS.get(cr.maturity_level, "#6b7280")
        gaps = "<br>".join(cr.gaps or []) or "None"
        remediation_count = len(cr.remediation or [])
        rows += (
            f"<tr>"
            f"<td><b>{cr.control_id}</b></td>"
            f"<td>{cr.control_name}</td>"
            f"<td style='color:{c};font-weight:bold'>ML{cr.maturity_level} — {cr.maturity_label}</td>"
            f"<td>{gaps}</td>"
            f"<td>{remediation_count} step(s)</td>"
            f"</tr>"
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>E8 Assessment — {machine.machine_label}</title>
  <style>
    body {{ font-family: sans-serif; margin: 2rem; background: #f9fafb; color: #111; }}
    h1 {{ color: #1e3a5f; }}
    .badge {{ display:inline-block; padding:.4rem 1.2rem; border-radius:6px;
              background:{overall_color}; color:#fff; font-size:1.3rem; font-weight:bold; }}
    table {{ border-collapse:collapse; width:100%; margin-top:1.5rem; background:#fff;
             box-shadow:0 1px 3px rgba(0,0,0,.1); border-radius:8px; overflow:hidden; }}
    th, td {{ border:1px solid #e5e7eb; padding:.7rem 1rem; text-align:left; vertical-align:top; }}
    th {{ background:#1e3a5f; color:#fff; }}
    tr:nth-child(even) {{ background:#f3f4f6; }}
    .meta {{ color:#6b7280; font-size:.9rem; margin:.5rem 0 1.5rem; }}
    .score {{ margin:1rem 0; }}
  </style>
</head>
<body>
  <h1>Essential Eight Compliance Assessment</h1>
  <div class="meta">
    Machine: <b>{machine.machine_label}</b> ({machine.fqdn or 'n/a'}) &nbsp;|&nbsp;
    OS: {machine.os_name} {machine.os_release or ''} &nbsp;|&nbsp;
    Assessed: {a.assessed_at.strftime('%Y-%m-%d %H:%M UTC')} &nbsp;|&nbsp;
    Target: ML{a.target_level}
  </div>
  <div class="score">
    Overall Maturity: <span class="badge">{a.overall_label}</span>
    &nbsp; Gaps: <b>{a.gap_count}</b> controls below ML3
  </div>
  <table>
    <thead>
      <tr>
        <th>ID</th><th>Control</th><th>Maturity</th><th>Gaps</th><th>Remediation</th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
  <p style="color:#9ca3af;font-size:.8rem;margin-top:2rem;">
    Generated by Essential Eight Compliance Tool &mdash; for internal use only.
  </p>
</body>
</html>"""
    return HTMLResponse(content=html)


@router.get("/dashboard/summary")
def dashboard_summary(
    db: Session = Depends(get_db),
    _: models.User = Depends(get_current_user),
):
    """Aggregate summary for the main dashboard."""
    machines = db.query(models.Machine).all()
    total = len(machines)
    if total == 0:
        return {"total_machines": 0, "average_maturity": None, "fully_compliant": 0, "controls": {}}

    latest_assessments = []
    for m in machines:
        latest = (
            db.query(models.Assessment)
            .filter_by(machine_id=m.id)
            .order_by(models.Assessment.assessed_at.desc())
            .first()
        )
        if latest:
            latest_assessments.append(latest)

    if not latest_assessments:
        return {"total_machines": total, "average_maturity": None, "fully_compliant": 0, "controls": {}}

    avg_maturity = sum(a.overall_maturity for a in latest_assessments) / len(latest_assessments)
    fully_compliant = sum(1 for a in latest_assessments if a.fully_compliant)

    # Per-control average maturity
    control_totals: dict = {}
    control_counts: dict = {}
    for a in latest_assessments:
        for cr in a.control_results:
            cid = cr.control_id
            control_totals[cid] = control_totals.get(cid, 0) + cr.maturity_level
            control_counts[cid] = control_counts.get(cid, 0) + 1

    control_averages = {
        cid: round(control_totals[cid] / control_counts[cid], 2)
        for cid in control_totals
    }

    return {
        "total_machines": total,
        "assessed_machines": len(latest_assessments),
        "average_maturity": round(avg_maturity, 2),
        "fully_compliant": fully_compliant,
        "controls": control_averages,
    }
